# Default values for mifos
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: fintecheando/com.mx.fintecheando.mifosx.18.03.01
  tag: latest
  pullPolicy: Always
service:
  name: mifos
  type: NodePort
  externalPort: 8443
  internalPort: 8443
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi